// generated by chatgpt
param nomeDaVM string = 'nome-da-vm'
param tamanhoDaVM string = 'Standard_DS1_v2'

resource grupoDeRecursos 'Microsoft.Resources/resourceGroups@2021-04-01' = {
  name: 'nome-do-grupo-de-recursos'
  location: 'nome-da-regiao'
}

resource maquinaVirtual 'Microsoft.Compute/virtualMachines@2021-03-01' = {
  name: nomeDaVM
  location: grupoDeRecursos.location
  properties: {
    hardwareProfile: {
      vmSize: tamanhoDaVM
    }
    storageProfile: {
      imageReference: {
        publisher: 'MicrosoftWindowsServer'
        offer: 'WindowsServer'
        sku: '2019-Datacenter'
        version: 'latest'
      }
      osDisk: {
        createOption: 'FromImage'
      }
    }
    osProfile: {
      computerName: nomeDaVM
      adminUsername: 'nome-do-usuario'
      adminPassword: 'senha-do-usuario'
    }
    networkProfile: {
      networkInterfaces: [
        {
          id: '${resourceId(grupoDeRecursos.name, 'Microsoft.Network/networkInterfaces', 'nome-da-nic')}'
        }
      ]
    }
  }
}

resource placaDeRede 'Microsoft.Network/networkInterfaces@2021-03-01' = {
  name: 'nome-da-nic'
  location: grupoDeRecursos.location
  properties: {
    ipConfigurations: [
      {
        name: 'config-ip'
        properties: {
          subnet: {
            id: '${resourceId(grupoDeRecursos.name, 'Microsoft.Network/virtualNetworks/subnets', 'nome-da-subnet')}'
          }
          privateIPAllocationMethod: 'Dynamic'
        }
      }
    ]
  }
}
